### ISSUE TITLE
Repo branches

### ISSUE THREAD

**Issue by artthik** [tageler/tageler-api#1]
Tried commiting edited README.md with small additional chapter preconditions, but got following error: 
<img width="534" alt="bildschirmfoto 2017-03-04 um 00 12 19" src="https://cloud.githubusercontent.com/assets/8858809/23572430/5314118e-006f-11e7-8f7c-0247d919a521.png">
1. What am I doing wrong?
2. Shall we make an own branch, is there an issue with rights?

Greets Art

**Comment by peschmae** [comment]
Committing directly against the master and develop branches are disabled, for those branches it's always necessary to have a successful travis-ci build (even for us), and the easiest way to achieve this, is to create a pull request (where travis ci will be triggered automatically).

Just create a new branch from you develop, push it to github and create the PR, we can then merge it to develop.

**Comment by artthik** [comment]
Ok. Now I see. Thx for the immediate help.
