### ISSUE TITLE
Language used in code

### ISSUE THREAD

**Issue by dukje** [tageler/tageler-api#3]
Dear @tageler/students-pse-17 
Please do only use english (and abbrevations of course) for varibales, comments, etc and appropriate names for tageler specific entities. For example in 9dfee2c8fe you might want to use variable names like _title_, _unit_, _start_, _end_, ...
Add it as glossary in the docu/readme (so you may ask question as issues and we can create change requests)?

**Comment by artthik** [comment]
Translated entities and variable names: https://github.com/tageler/tageler-api/commit/1d080e2f8e5d2c2ffb1eb759a368daace7ffbd2a
Added chapter `Glossary`to `README.md`: https://github.com/tageler/tageler-api/commit/ffe2ef977a1d7f71da7145417d969f518f227fe8
If you have any better names or suggestions we'll be happy to adjust our names.
