### ISSUE TITLE
api-model unit

### ISSUE THREAD

**Issue by doutzi** [tageler/tageler-api#4]
- [x] implement in: /src.controllers.unitController.js
- [x] schema: ~~unit_name, something else needed?~~ *type:String, enum:['Meute','Trupp','Equipe']* and *name: String*
- [x] create: /src.models.unitModel.js
- [x] update: /src.routes.js and other dependencies

**Comment by Manning94** [comment]
would be nice if colleagues check what i have done :D

**Comment by lebalz** [comment]
refactored the basic implementation from @Manning94, create&read works now, update&delete still has to be done.
